### ISSUE TITLE
Identify device call failed!

### ISSUE THREAD

**Issue by ajcr07** [pig1800/WD4kConverter#1]
I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0

OS: Windows 10 21H1

And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.

**Comment by pig1800** [comment]
Hi The program using ATA Pass Through for sending WD customized SMART commands.I’m not sure if it works on USB devices… And I’m also not sure if WD Elements drives supports sector size change.But if it says “Identify device call failed”, then it means it cannot access drive through low-level ATA commands. Maybe you can try pry it open and connect with SATA? Sent from Mail for Windows From: ajcr07Sent: Friday, December 31, 2021 7:20To: pig1800/WD4kConverterCc: SubscribedSubject: [pig1800/WD4kConverter] Identify device call failed! (Issue #1) I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0OS: Windows 10 21H1And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by pig1800** [comment]
The program uses ATA Pass-Through for sending WD customized SMART commands.
I’m not sure if it works on USB devices…
 
And I’m also not sure if WD Elements drives support sector size change.
But if it says “Identify device call failed,” it means it cannot access the drive through low-level ATA commands.
 
Can you try to pry it open and connect with SATA and give me a result?

Btw, This program tends to be used with Datacenter drives as described in README.

**Comment by 991547436** [comment]
> I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> 
> OS: Windows 10 21H1
> 
> And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.

WD HC550 18T in usb can't format, in sata can format

**Comment by pig1800** [comment]
> > I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> > OS: Windows 10 21H1
> > And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.
> 
> WD HC550 18T in usb can't format, in sata can format

Thank you for the report, glad to see my program worked properly as predicted. I'd like to ask if your "format" means using my program to change the sector size?
感谢测试，确认一下你的这个format的意思指的是用我的程序切换扇区尺寸吗？

**Comment by 991547436** [comment]
> > > I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> > > OS: Windows 10 21H1
> > > And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.
> > 
> > 
> > WD HC550 18T in usb can't format, in sata can format
> 
> Thank you for the report, glad to see my program worked properly as predicted. I'd like to ask if your "format" means using my program to change the sector size? 感谢测试，确认一下你的这个format的意思指的是用我的程序切换扇区尺寸吗？

是的 用你的工具或hugo通过sata线连电脑是可以转换成4kn的  用usb硬盘盒两者都不能转换

**Comment by pig1800** [comment]
> > > > I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> > > > OS: Windows 10 21H1
> > > > And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.
> > > 
> > > 
> > > WD HC550 18T in usb can't format, in sata can format
> > 
> > 
> > Thank you for the report, glad to see my program worked properly as predicted. I'd like to ask if your "format" means using my program to change the sector size? 感谢测试，确认一下你的这个format的意思指的是用我的程序切换扇区尺寸吗？
> 
> 是的 用你的工具或hugo通过sata线连电脑是可以转换成4kn的 用usb硬盘盒两者都不能转换

感谢汇报！

**Comment by PaTTeeL** [comment]
> > > > I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> > > > OS: Windows 10 21H1
> > > > And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.
> > > 
> > > 
> > > WD HC550 18T in usb can't format, in sata can format
> > 
> > 
> > Thank you for the report, glad to see my program worked properly as predicted. I'd like to ask if your "format" means using my program to change the sector size? 感谢测试，确认一下你的这个format的意思指的是用我的程序切换扇区尺寸吗？
> 
> 是的 用你的工具或hugo通过sata线连电脑是可以转换成4kn的 用usb硬盘盒两者都不能转换

问问转换后硬盘上的数据还在吗？
根据
https://superuser.com/questions/1576894/how-to-convert-the-western-digital-ultrastar-dc-hc530-14tb-hdd-from-512e-to-4
这条问答的说法：
```
I successfully changed the logical sector size from 512 to 4096 for my HC530 14TB drive. Since only logical sector size is changed, and the physical sector size remains 4096 all the time, this operation won't affect existing data on the disk; however it is always recommended to backup any important data before trying any operation like this.
```
转化512e到4kn没有数据的损失？

**Comment by pig1800** [comment]
> 

程序中已经说明，数据本身不会有任何变化，但是文件系统是和扇区大小硬相关，虽然硬盘中每一个字节都没有变化，但是文件系统会无法识别任何文件

**Comment by pig1800** [comment]
> > > > > I'm getting this error: Identify device call failed! when trying this tool on a WD Elements 14TB WD140EDGZ-11B1PA0
> > > > > OS: Windows 10 21H1
> > > > > And yes I did run it in a command prompt with admin rights, also the official WD tool Hugo worked with this drive.
> > > > 
> > > > 
> > > > WD HC550 18T in usb can't format, in sata can format
> > > 
> > > 
> > > Thank you for the report, glad to see my program worked properly as predicted. I'd like to ask if your "format" means using my program to change the sector size? 感谢测试，确认一下你的这个format的意思指的是用我的程序切换扇区尺寸吗？
> > 
> > 
> > 是的 用你的工具或hugo通过sata线连电脑是可以转换成4kn的 用usb硬盘盒两者都不能转换
> 
> 问问转换后硬盘上的数据还在吗？ 根据 https://superuser.com/questions/1576894/how-to-convert-the-western-digital-ultrastar-dc-hc530-14tb-hdd-from-512e-to-4 这条问答的说法：
> 
> ```
> I successfully changed the logical sector size from 512 to 4096 for my HC530 14TB drive. Since only logical sector size is changed, and the physical sector size remains 4096 all the time, this operation won't affect existing data on the disk; however it is always recommended to backup any important data before trying any operation like this.
> ```
> 
> 转化512e到4kn没有数据的损失？

程序中已经说明，数据本身不会有任何变化，但是文件系统是和扇区大小硬相关，虽然硬盘中每一个字节都没有变化，但是文件系统会无法识别任何文件
