### ISSUE TITLE
HUH721010ALE600 gives error

### ISSUE THREAD

**Issue by jacobacci** [pig1800/WD4kConverter#2]
From what I have read in several forums, HUH721010ALE600 should be convertable from 512e to 4kn. The drive is found by WD4kConverter, but the process is aborted with an error message:

<img width="661" alt="4kn Konversion geht leider nicht" src="https://user-images.githubusercontent.com/10114193/198339136-40f26073-8f64-4ef2-b0f8-ae1378aec249.png">

![HGST](https://user-images.githubusercontent.com/10114193/198339364-88bf976c-af4d-426f-8e97-cfae2f6f37a9.jpg)

**Comment by pig1800** [comment]
Read this document carefully:
https://documents.westerndigital.com/content/dam/doc-library/en_us/assets/public/western-digital/product/data-center-drives/ultrastar-sata-series/product-manual-ultrastar-dc-hc510-sata-oem-spec.pdf

Right after table of contents, in 1.1 Introduction, you can see for HC510, sector size is hard coded for each model and cannot be changed by software.

**Comment by jacobacci** [comment]
Thanks for the clarification
