### ISSUE TITLE
Please HELP.

### ISSUE THREAD

**Issue by Zibri** [pig1800/WD4kConverter#3]
Hello!
I have a WD My Book 14 TB
Inside there is a WDC WD140EDGZ-11B1PA0

I was trying to change the block size to 4096.. I tried almost everything including sg3_utils with various commands.
Today at a certain point my drive switched to 4096!
Even if smartcts still reports 512/4096 for some reason, if I issue the command:

```
dev=$(sg_scan |grep "My Book"|cut -d' ' -f 1)
sz=$(sg_raw 2>/dev/null -r 40 $dev 9e 10 00 00 00 00 00 00 00 00 00 00 00 0c 00 00 -b|xxd -p)
nb=$((0x${sz:0:16}))
bs=$((0x${sz:17:23}))
echo HDD Size: $((nb*bs))
echo Block Size: $bs

```
Now it says 4096 ! Also opening the drive in HxD it says that there are 3'418'095'616 sectors!

Now I wish to set it back to 512!
I read from other comments here that it's not possible if it is in the enclosure, but that's not true, because I changed it to 4096 while it was in the enclosure!

Please help.

**Comment by Zibri** [comment]
C:\Users\Zibri\Downloads\openSeaChest-refs-tags-v22.07-win-x64>openSeaChest_Erase.exe -d PD2 -i

 openSeaChest_Erase - openSeaChest drive utilities - NVMe Enabled
 Copyright (c) 2014-2022 Seagate Technology LLC and/or its Affiliates, All Rights Reserved
 openSeaChest_Erase Version: 3.2.0-3_2_1 X86_64
 Build Date: Jul 26 2022
 Today: Sun Jan 22 07:25:52 2023        User: Zibri (admin)

\\.\PhysicalDrive2 - My Book 25ED - XHG5AL6D - 1031 - ATA
        Vendor ID: WD
        Model Number: My Book 25ED
        Serial Number: ********
        Firmware Revision: 1031
        World Wide Name: 5000CCA299C26D99
        Drive Capacity (TB/TiB): 14.00/12.73
        Temperature Data:
                Current Temperature (C): 45
                Highest Temperature (C): 47
                Lowest Temperature (C): 23
        Power On Time:  1 day 9 hours
        Power On Hours: 33.00
        **MaxLBA: 3418095615
        Native MaxLBA: Not Reported
        Logical Sector Size (B): 4096
        Physical Sector Size (B): 4096**
        Sector Alignment: 0
        Rotation Rate (RPM): 7200
        Form Factor: 3.5"
        Last DST information:
                DST has never been run
        Long Drive Self Test Time:  1 day 3 hours 36 minutes
        Interface speed:
                Max Speed (Gb/s): 6.0
                Negotiated Speed (Gb/s): 6.0
        Annualized Workload Rate (TB/yr): 31.43
        Total Bytes Read (GB): 114.82
        Total Bytes Written (GB): 3.58
        Encryption Support: Full Disk Encryption
        Cache Size (MiB): 512.00
        Read Look-Ahead: Enabled
        Write Cache: Enabled
        SMART Status: Good
        ATA Security Information: Supported
        Firmware Download Support: Full, Segmented, Deferred, DMA
        Specifications Supported:
                ACS-2
                ATA8-ACS
                ATA/ATAPI-7
                ATA/ATAPI-6
                ATA/ATAPI-5
                ATA/ATAPI-4
                ATA-3
                ATA-2
                SATA 3.2
                SATA 3.1
                SATA 3.0
                SATA 2.6
                SATA 2.5
                SATA II: Extensions
                SATA 1.0a
                ATA8-AST
                SPC-4
                USB-BOT
                SPC-4
                SBC-3
                SAT-3
        Features Supported:
                TCG
                Sanitize
                SATA NCQ
                SATA NCQ Streaming
                SATA Rebuild Assist
                SATA Software Settings Preservation
                SATA In-Order Data Delivery
                SATA Device Initiated Power Management
                HPA
                Power Management
                Security
                SMART [Enabled]
                DCO
                48bit Address
                PUIS
                APM
                GPL
                Streaming
                SMART Self-Test
                SMART Error Logging
                EPC [Enabled]
                Sense Data Reporting
                SCT Write Same
                SCT Error Recovery Control
                SCT Feature Control
                SCT Data Tables
                Host Logging
                Set Sector Configuration
                Storage Element Depopulation
        Adapter Information:
                Adapter Type: USB
                Vendor ID: 1058h
                Product ID: 25EDh
                Revision: 1031h

**Comment by Zibri** [comment]
And also:
$ sg_raw -r 512 $dev 25 00 00 00 00 00 00 00 00 00
SCSI Status: Good

Received 8 bytes of data:
 00     cb bb ff ff 00 00 10 00                             ........

read capacity command says:
CBBBFFFF = 3418095615 blocks
and 1000 = 4096 bytes per block.

**Comment by pig1800** [comment]
I don't have such disk and I can't offer any help.
This program is supposed to work over direct SATA connection, because it is using ATA Pass-Through function provided by Windows, and I made this program because I want do all the work under Windows.
You are using Linux, and using USB, and it's not a WD DC drive, please don't make such issue because it's nothing related to my program.

**Comment by Zibri** [comment]
Perfect... it also explains the origin of your nickname. Anyway, not thanks to you I solved the problem.
