### ISSUE TITLE
What about Toshiba and other Vendors ?

### ISSUE THREAD

**Issue by ghost** [pig1800/WD4kConverter#5]
What about Toshiba and other Vendors ?

Get-Disk and fsutil show 4096 physical sectors on most disks already.

How to force conversion on other vendors?

**Comment by pig1800** [comment]
Every vendor has their own custom command, some are publicly available, some are not, and some doesn't even have ability to change it after the manufacture.
I have only WD HC drives so I made this tool, other brands and product lines are out of my reach.

**Comment by ghost** [comment]
They also sell the same product with possibly different firmware and model number difference. However having the ability to send the command anyway, is a good thing to have. Does smartmontools have different commands per vendor/model ?

**Comment by pig1800** [comment]
I don't know, but I don't think smartmontools can do the actual change by itself, read the Thanks part of the Readme, the guy from the first link used "camcontrol" utility to send hex values directly to drive to change the sector size.

**Comment by ghost** [comment]
What if we wireshark the USB traffic from the USB to SATA adapter and sniff the commands from some official and some service tools ? Maybe then we can get some commands to 'force' on some storage models that otherwise are 'not officially convertible' ?

**Comment by pig1800** [comment]
That will be hella mess, you have to unpack all the way through USB to UASP to SCSI to ATA to get the actual control command...

**Comment by ghost** [comment]
I think Wireshark does that already this was the idea.

**Comment by pig1800** [comment]
oh? I thought Wireshark only captures USB packet... so it's that intelligent now?
if so, then it's definitely an option, start capture, send command, check how the command is constructed, and write a program to verify it.
Totally possible, of course.

**Comment by ghost** [comment]
Still much better to be able to look at and analyze PCI-e and SATA traffic rather than USB because the vendor tools seem to support only certain enterprise PCIe controllers to change sector size (Hugo documentation)

**Comment by andika207** [comment]
question, does it support the current line of WD RED or BLUE drives ?

**Comment by pig1800** [comment]
> question, does it support the current line of WD RED or BLUE drives ?

I don't think those drives even have ability to change sector size.

**Comment by dsolaray** [comment]
> > question, does it support the current line of WD RED or BLUE drives ?
> 
> I don't think those drives even have ability to change sector size.

The red and blue drives are based on the DC Ultrastar platform.
the white label drives supplied inside USB plastic enclosures do support 4K sectors.
